name: Deploy to Netlify on Push to Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Site to Netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
